# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8dace259f6a29636182fb26b30fdb71b6c05628b1242733d0546bc55edcc3cfe51d41d75707f9a409f28b99af2d024a63c4929f52fb579bd5b9f503584fb9c1

test:
  secret_key_base: 997694e561a7278d51d190070e051a903327ca6b897dec72e9e46f1d758828306f072d37f469fea41079e424b66350043c4d1165e36da821dcb3acf8eba54927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
